#!/usr/bin/env bash
set -Eeuo pipefail

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERITAS_ROOT="$(cd "$INSTALL_DIR/.." && pwd)"
source "$INSTALL_DIR/versions.env"

LOCK_DIR="$INSTALL_DIR/locks"
SOURCE_LOCK="$LOCK_DIR/source-revisions.env"
mkdir -p "$LOCK_DIR"

log(){ printf '\n\033[1;34m[VERITAS]\033[0m %s\n' "$*"; }
ok(){ printf '\033[1;32m[OK]\033[0m %s\n' "$*"; }
warn(){ printf '\033[1;33m[WARN]\033[0m %s\n' "$*" >&2; }
die(){ printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

miniforge_root(){ printf '%s\n' "${VERITAS_MINIFORGE_ROOT:-$HOME/miniforge3}"; }

source_conda(){
  local r
  r="$(miniforge_root)"
  [[ -f "$r/etc/profile.d/conda.sh" ]] || die "Missing $r/etc/profile.d/conda.sh"
  # shellcheck disable=SC1090
  source "$r/etc/profile.d/conda.sh"
}

activate_veritas(){
  source_conda
  conda activate "$CONDA_ENV_NAME"
}

resolve_source_locks(){
  command -v git >/dev/null || die "git is required"
  mkdir -p "$LOCK_DIR"

  if [[ -f "$SOURCE_LOCK" ]]; then
    # shellcheck disable=SC1090
    source "$SOURCE_LOCK"
  fi

  [[ -n "${DOLFINX_MATERIALS_COMMIT:-}" ]] || \
    DOLFINX_MATERIALS_COMMIT="$(git ls-remote "$DOLFINX_MATERIALS_REPO" HEAD | awk '{print $1}')"
  [[ -n "${COMODO_COMMIT:-}" ]] || \
    COMODO_COMMIT="$(git ls-remote "$COMODO_REPO" HEAD | awk '{print $1}')"
  [[ -n "${GEOGRAMJL_COMMIT:-}" ]] || \
    GEOGRAMJL_COMMIT="$(git ls-remote "$GEOGRAMJL_REPO" HEAD | awk '{print $1}')"
  [[ -n "${GEOGRAM_COMMIT:-}" ]] || \
    GEOGRAM_COMMIT="$(git ls-remote "$GEOGRAM_REPO" HEAD | awk '{print $1}')"

  [[ -n "$DOLFINX_MATERIALS_COMMIT" && -n "$COMODO_COMMIT" && \
     -n "$GEOGRAMJL_COMMIT" && -n "$GEOGRAM_COMMIT" ]] || \
    die "Could not resolve source revisions"

  cat > "$SOURCE_LOCK" <<EOF_LOCK
# Generated by VERITAS installation. Commit this file for reproducibility.
DOLFINX_MATERIALS_COMMIT="$DOLFINX_MATERIALS_COMMIT"
COMODO_COMMIT="$COMODO_COMMIT"
GEOGRAMJL_COMMIT="$GEOGRAMJL_COMMIT"
GEOGRAM_COMMIT="$GEOGRAM_COMMIT"
EOF_LOCK

  export DOLFINX_MATERIALS_COMMIT COMODO_COMMIT GEOGRAMJL_COMMIT GEOGRAM_COMMIT
}
